version: 2

workflows:
  version: 2
  test:
    jobs:
      - fmt
      - lint
      - test
      - vet
  release:
    jobs:
      - release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              # Only on tags formatted like v0.1.1
              only: /^v\d+\.\d+\.\d+[0-9A-Za-z-]*$/

jobs:
  fmt:
    docker:
      - image: golang:1.18
    working_directory: /go/src/github.com/skpr/cloudfront-invalidation-metrics
    steps:
      - checkout
      - run: |
          go mod vendor
          go fmt ./...
  test:
    docker:
      - image: golang:1.18
    working_directory: /go/src/github.com/skpr/cloudfront-invalidation-metrics
    steps:
      - checkout
      - run: |
          go mod vendor
          go test ./...
  lint:
    docker:
      - image: golang:1.18
    working_directory: /go/src/github.com/skpr/cloudfront-invalidation-metrics
    steps:
      - checkout
      - run: |
          docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.45.2 golangci-lint run -v
  vet:
    docker:
      - image: golang:1.18
    working_directory: /go/src/github.com/skpr/cloudfront-invalidation-metrics
    steps:
      - run: |
          go mod vendor
          go vet ./...

  release:
    docker:
      - image: docker.io/goreleaser/goreleaser:v0.174.2
    working_directory: /go/src/github.com/skpr/cloudfront-invalidation-metrics
    steps:
      - checkout
      - run: goreleaser
